name: cast_me_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path: ^1.8.0
  protobuf: ^2.1.0
  firebase_core: ^1.18.0
  just_audio: ^0.9.27
  audio_session: ^0.1.9
  rxdart: ^0.27.4
  cloud_firestore: ^3.4.0
  async_list_view: ^1.0.1
  firebase_storage: ^10.3.4
  firebase_image: ^1.1.1
  firebase_auth: ^3.6.2
  flutter_login: ^4.0.0
  flutterfire_ui: ^0.4.3+4
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: CastMe
      fonts:
        - asset: fonts/CastMe.ttf
