name: cast_me_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path: ^1.8.0
  protobuf: ^2.1.0
  firebase_core: ^1.18.0
  just_audio: ^0.9.27
  audio_session: ^0.1.9
  rxdart: ^0.27.4
  async_list_view: ^1.0.1
  image_picker: ^0.8.5+3
  file_picker: ^5.0.1
  palette_generator: ^0.3.3+1
  shared_preferences: ^2.0.15
  connectivity_plus: ^2.3.6
  supabase_flutter: ^0.3.3
  basic_utils: ^4.5.2
  ffmpeg_kit_flutter: ^4.5.1
  crypto: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.0

# To rebuild run: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/cast_me_icon_android.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/cast_me_icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: CastMe
      fonts:
        - asset: fonts/CastMe.ttf
