name: cast_me_app
description: A new Flutter project.
publish_to: 'none'

version: 0.2.10+41

# flutter pub run pubspec_dependency_sorter

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path: ^1.8.0
  protobuf: ^2.1.0
  just_audio: ^0.9.31
  audio_session: ^0.1.9
  rxdart: ^0.27.4
  async_list_view: ^1.0.2
  image_picker: ^0.8.5+3
  file_picker: ^5.2.0+1
  palette_generator: ^0.3.3+1
  shared_preferences: ^2.0.15
  connectivity_plus: ^3.0.2
  supabase_flutter: ^1.4.0
  basic_utils: ^5.4.2
  ffmpeg_kit_flutter_audio: ^5.1.0
  crypto: ^3.0.2
  package_info_plus: ^3.0.2
  firebase_analytics: ^10.0.6
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6
  firebase_messaging: ^14.1.1
  audio_service: ^0.18.7
  launch_review: ^3.0.1
  implicit_navigator:
    path: ../implicit_navigator
  intl: ^0.18.0
  image_cropper: ^3.0.0
  mime: ^1.0.2
  share_handler: ^0.0.16
  record: ^4.4.0
  just_the_tooltip: ^0.0.12
  path_provider: ^2.0.11
  cached_network_image: ^3.2.2
  share_plus: ^6.0.0
  flutter_signin_button: ^2.0.0
  uni_links: ^0.5.1
  collection: ^1.16.0
  badges: ^3.0.2
  social_share: ^2.2.1
  font_awesome_flutter: ^9.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  boxy: ^2.0.6+2
  adaptive_material: ^0.1.1
  device_info_plus: ^8.0.0
  animations: ^2.0.7
  wakelock: ^0.6.2
  flutter_keyboard_visibility: ^5.4.0
  expandable_page_view: ^1.0.17
  device_frame: ^1.1.0
  visibility_detector: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0
  # flutter pub run import_sorter:main
  import_sorter: ^4.6.0
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_android: "assets/icons/cast_me_icon_android.png"
  image_path_ios: "assets/icons/cast_me_icon_ios.png"
  adaptive_icon_background: "#19191F"
  adaptive_icon_foreground: "assets/icons/cast_me_icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: CastMe
      fonts:
        - asset: fonts/CastMe.ttf
