/// Flutter icons CastMe
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CastMe
///      fonts:
///       - asset: fonts/CastMe.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons{
  CustomIcons._();

  static const _kFontFam = 'CastMe';
  static const String? _kFontPkg = null;

  static const IconData cast_me = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
